// constants.js file contains constants data

const LOGO_URL =
  "https://png.pngtree.com/png-vector/20220708/ourmid/pngtree-fast-food-logo-png-image_5763171.png";

const CDN_URL =
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";

const RestaurantsMenuCards__Dummy = [
  {
    id: 1003414,
    name: "Pizza Hut",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +
      "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/9/a1e023e4-bdf3-4bcb-b4d9-2498ba52528e_1003414.JPG",
    menu: [
      {
        itemName: "Panner pizza",
        itemId: 1,
        price: "169",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Tomato pizza",
        itemId: 2,
        price: "120",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Margherita pizza",
        itemId: 3,
        price: "169",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Tandoori Chicken pizza",
        itemId: 4,
        price: "250",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Mushroom pizza",
        itemId: 5,
        price: "199",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
    ],
  },
  {
    id: 234875,
    name: "Adil Hotel",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +
      "gp1ityra6utvzqn6ghnv",
    menu: [
      {
        itemName: "Veg Biryani",
        itemId: 1,
        price: "149",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Mushroom Biryani ",
        itemId: 2,
        price: "169",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Dum Biryani",
        itemId: 3,
        price: "249",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Fry Biryani",
        itemId: 4,
        price: "220",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken 65",
        itemId: 5,
        price: "99",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chillie Chicken",
        itemId: 6,
        price: "129",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Masala Panner",
        itemId: 7,
        price: "99",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
    ],
  },
  {
    id: 630193,
    name: "Champaran Handi Restaurant",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +
      "xph0vf5pvbxjf8xchwjk",
    menu: [
      {
        itemName: "Veg Biryani",
        itemId: 1,
        price: "149",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Mushroom Biryani ",
        itemId: 2,
        price: "169",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Dum Biryani",
        itemId: 3,
        price: "249",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Fry Biryani",
        itemId: 4,
        price: "220",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken 65",
        itemId: 5,
        price: "99",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chillie Chicken",
        itemId: 6,
        price: "129",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Masala Panner",
        itemId: 7,
        price: "99",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
    ],
  },
  {
    id: 618037,
    name: "Jai Ganesh Bhojnalaya",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +
      "yzgqriufpzmloogcn2vl",
    menu: [
      {
        itemName: "Veg Biryani",
        itemId: 1,
        price: "149",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Mushroom Biryani ",
        itemId: 2,
        price: "169",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Dum Biryani",
        itemId: 3,
        price: "249",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Fry Biryani",
        itemId: 4,
        price: "220",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken 65",
        itemId: 5,
        price: "99",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chillie Chicken",
        itemId: 6,
        price: "129",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Masala Panner",
        itemId: 7,
        price: "99",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
    ],
  },
  {
    id: 151515,
    name: "Gupta Bhojnalay",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +
      "jo9pdipf4elcuch8g55q",
    menu: [
      {
        itemName: "Veg Biryani",
        itemId: 1,
        price: "149",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Mushroom Biryani ",
        itemId: 2,
        price: "169",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Dum Biryani",
        itemId: 3,
        price: "249",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Fry Biryani",
        itemId: 4,
        price: "220",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken 65",
        itemId: 5,
        price: "99",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chillie Chicken",
        itemId: 6,
        price: "129",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Masala Panner",
        itemId: 7,
        price: "99",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
    ],
  },
  {
    id: 151648,
    name: "Mr. Gurung Momo & Chinese Corner",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +
      "h7oibtpm7kqks8cqz3gh",
    menu: [
      {
        itemName: "Veg Biryani",
        itemId: 1,
        price: "149",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Mushroom Biryani ",
        itemId: 2,
        price: "169",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Dum Biryani",
        itemId: 3,
        price: "249",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Fry Biryani",
        itemId: 4,
        price: "220",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken 65",
        itemId: 5,
        price: "99",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chillie Chicken",
        itemId: 6,
        price: "129",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Masala Panner",
        itemId: 7,
        price: "99",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
    ],
  },
  {
    id: 615927,
    name: "Roof 5",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +
      "glepanv4xjfnhsbieam1",
    menu: [
      {
        itemName: "Veg Biryani",
        itemId: 1,
        price: "149",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Mushroom Biryani ",
        itemId: 2,
        price: "169",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Dum Biryani",
        itemId: 3,
        price: "249",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Fry Biryani",
        itemId: 4,
        price: "220",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken 65",
        itemId: 5,
        price: "99",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chillie Chicken",
        itemId: 6,
        price: "129",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Masala Panner",
        itemId: 7,
        price: "99",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
    ],
  },
  {
    id: 184424,
    name: "Sab Ghar Tak Foods",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" +
      "ryzswg44bt7thqzkuaj4",
    menu: [
      {
        itemName: "Veg Biryani",
        itemId: 1,
        price: "149",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
      {
        itemName: "Mushroom Biryani ",
        itemId: 2,
        price: "169",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Dum Biryani",
        itemId: 3,
        price: "249",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken Fry Biryani",
        itemId: 4,
        price: "220",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chicken 65",
        itemId: 5,
        price: "99",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Chillie Chicken",
        itemId: 6,
        price: "129",
        ingredients: [],
        category: "non-veg",
        itemImageUrl: "",
      },
      {
        itemName: "Masala Panner",
        itemId: 7,
        price: "99",
        ingredients: [],
        category: "veg",
        itemImageUrl: "",
      },
    ],
  },
];

export { LOGO_URL, CDN_URL, RestaurantsMenuCards__Dummy };
